#!/usr/bin/env bun
// kilocode_change - new file
//
// Mock SQL/CSV MCP server for the Resoft CodingAgent V1 starter.
//
// What this is:
//   A stdio MCP server that implements two tools — `mock_sql_query` and
//   `mock_csv_list` — against a small synthetic dataset so the V1 regulatory
//   reporting agents (quality-analyst, etl-developer, data-tester,
//   data-analyst) have something concrete to call during local development,
//   CI smoke tests, and demos. It is NOT a real database; the queries are
//   pattern-matched to deterministic mock responses so the agent loop can
//   be exercised end-to-end without spinning up a SQL engine.
//
// How to use it:
//   1. Direct stdio launch: `bun run src/kilocode/resoft/mcp-mock-server.ts`
//   2. From a `.kilo/mcp.json` block generated by `resoft init --with-mcp`.
//   3. From a unit test, via the MCP client SDK over stdio.
//
// Environment knobs:
//   RESOFT_MOCK_DB        — dataset name (default: "regulatory_demo")
//   RESOFT_MOCK_FAIL_QUERY — set to "1" to make mock_sql_query throw (used
//                            to test the agent's error-handling lane)
//   RESOFT_MOCK_DELAY_MS  — optional per-call latency in ms (default 0)

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js"
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js"
import { z } from "zod"

const DATASET = process.env["RESOFT_MOCK_DB"] ?? "regulatory_demo"
const FAIL_QUERY = process.env["RESOFT_MOCK_FAIL_QUERY"] === "1"
const DELAY_MS = Number.parseInt(process.env["RESOFT_MOCK_DELAY_MS"] ?? "0", 10) || 0

const TABLES: Record<string, { columns: string[]; rows: string[][] }> = {
  regulatory_demo: {
    columns: ["report_period", "branch_id", "metric_code", "amount", "currency"],
    rows: [
      ["2025Q4", "BJ-001", "RWA_TOTAL", "1823450112.55", "CNY"],
      ["2025Q4", "BJ-001", "NPL_RATIO", "1.42", "PCT"],
      ["2025Q4", "SH-014", "RWA_TOTAL", "998210445.10", "CNY"],
      ["2025Q4", "SH-014", "NPL_RATIO", "0.97", "PCT"],
      ["2025Q4", "GZ-027", "RWA_TOTAL", "542100876.42", "CNY"],
      ["2025Q4", "GZ-027", "NPL_RATIO", "2.18", "PCT"],
    ],
  },
  loan_portfolio: {
    columns: ["loan_id", "customer_id", "principal", "outstanding", "status"],
    rows: [
      ["L0001", "C100023", "500000", "412000", "current"],
      ["L0002", "C100099", "1200000", "1200000", "delinquent_30"],
      ["L0003", "C100188", "85000", "0", "written_off"],
    ],
  },
}

const server = new McpServer({
  name: "resoft-mock-sql",
  version: "0.1.0",
})

server.tool(
  "mock_sql_query",
  "Run a mock SQL query against the synthetic regulatory dataset. Recognised " +
    "shapes: `SELECT ... FROM <table>`, `SELECT COUNT(*) FROM <table>`, " +
    "`SHOW TABLES`. Unknown queries return a synthetic two-row preview so the " +
    "agent loop still has evidence to act on. Set RESOFT_MOCK_FAIL_QUERY=1 in " +
    "the server environment to make every call throw — useful for testing the " +
    "agent's error lane.",
  {
    sql: z.string().min(1).describe("SQL-like query string. Case-insensitive."),
    row_limit: z
      .number()
      .int()
      .positive()
      .max(1000)
      .optional()
      .describe("Cap on rows returned. Defaults to 100."),
  },
  async ({ sql, row_limit }) => {
    if (DELAY_MS > 0) await new Promise((r) => setTimeout(r, DELAY_MS))
    if (FAIL_QUERY) {
      return {
        isError: true,
        content: [{ type: "text" as const, text: `mock_sql_query forced failure: ${sql.slice(0, 80)}` }],
      }
    }
    const limit = row_limit ?? 100
    const trimmed = sql.trim().replace(/;$/, "")
    const upper = trimmed.toUpperCase()
    if (upper.startsWith("SHOW TABLES")) {
      const names = Object.keys(TABLES)
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify({ dataset: DATASET, tables: names }, null, 2),
          },
        ],
      }
    }
    const m = upper.match(/FROM\s+([A-Z0-9_]+)/)
    const tableKey = m ? m[1]!.toLowerCase() : ""
    const table = TABLES[tableKey]
    if (!table) {
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(
              {
                dataset: DATASET,
                rows: [],
                note: `mock table "${tableKey}" not found; available: ${Object.keys(TABLES).join(", ")}`,
              },
              null,
              2,
            ),
          },
        ],
      }
    }
    if (upper.includes("COUNT(*)")) {
      return {
        content: [
          {
            type: "text" as const,
            text: JSON.stringify(
              { dataset: DATASET, table: tableKey, columns: table.columns, count: table.rows.length },
              null,
              2,
            ),
          },
        ],
      }
    }
    const slice = table.rows.slice(0, limit)
    return {
      content: [
        {
          type: "text" as const,
          text: JSON.stringify({ dataset: DATASET, table: tableKey, columns: table.columns, rows: slice }, null, 2),
        },
      ],
    }
  },
)

server.tool(
  "mock_csv_list",
  "List synthetic CSV files available in the configured mock dataset. Returns " +
    "file names, sizes, and row counts so an ETL agent can plan a load step " +
    "without a real filesystem.",
  {
    dir: z
      .string()
      .optional()
      .describe("Logical directory. Defaults to the active dataset root."),
  },
  async ({ dir }) => {
    if (DELAY_MS > 0) await new Promise((r) => setTimeout(r, DELAY_MS))
    const files = [
      { name: `${DATASET}_loan_portfolio_2025Q4.csv`, size: 1024, rows: 1000 },
      { name: `${DATASET}_rwa_summary_2025Q4.csv`, size: 512, rows: 220 },
      { name: `${DATASET}_reconciliation_2025Q4.csv`, size: 256, rows: 48 },
    ]
    return {
      content: [
        { type: "text" as const, text: JSON.stringify({ dataset: DATASET, dir: dir ?? "/", files }, null, 2) },
      ],
    }
  },
)

async function main() {
  const transport = new StdioServerTransport()
  await server.connect(transport)
  // Surface a single line on stderr so a test that spawns the server
  // can wait for it without depending on MCP initialization timing.
  process.stderr.write(`resoft-mock-sql ready dataset=${DATASET}\n`)
}

main().catch((err) => {
  process.stderr.write(`resoft-mock-sql fatal: ${err instanceof Error ? err.stack ?? err.message : String(err)}\n`)
  process.exit(1)
})
